import React from 'react';
import LineChart from '../components/LineChart';
import styles from '../styles/Slug.module.css';
import Head from 'next/head';
import Link from 'next/link';
import dynamic from 'next/dynamic';


const LeafletMap = dynamic(() => import('../components/LeafletMap'), {
    loading: () => <p>A map is loading</p>,
      ssr: false
    });


export default function slug({country, updateData }) {
    return (

       <div className={styles.slugwrapper}>   
            <Head>
                <title>{country.Country} COVID-19 DATA</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href={"https://flagcdn.com/"+country.CountryCode.toLowerCase()+".svg"} />
            </Head>
            <div className={styles.slugcontainer}>
                <div className={styles.bannercontainer}>

                    <div className={styles.banner}>
                        <img  src={"https://flagcdn.com/"+country.CountryCode.toLowerCase()+".svg"} alt={country.Country}/>
                    </div> 

                    <div className={styles.bannerinfo}>
                        <h1 className={styles.countryname}>{country.Country} {country.CountryCode}</h1>
                        <h3 className={styles.rates}> Recovery Rate : {100 * (country.TotalRecovered/country.TotalConfirmed).toFixed(2)} %</h3>
                        <h3 className={styles.rates}> Mortality Rate : {100 * (country.TotalDeaths/country.TotalConfirmed).toFixed(2)} %</h3>
                        <Link href={"/"}><a className={styles.btnwrapper}> <div className={styles.btncontainer}> <img src="./prev.svg"/> </div><span>Back</span></a></Link>
                    </div>
   
                </div>

                <div className={styles.infosection}>

                    <div className={styles.mapsection}>

                        <div className={styles.map}>
                            <LeafletMap updateData = {updateData[0]}/>
                        </div>

                        <div className={styles.mapinformation}>
                            <p className={styles.cases}>
                                <span className={styles.data}>New Confirmed : {country.NewConfirmed}</span>
                                <span className={styles.data} >New Deaths : {country.NewDeaths}</span>
                                <span className={styles.data}>New Recovered : {country.NewRecovered}</span>
                            </p>
                            
                            <p className={styles.cases}>
                                <span className={styles.data}>Total Confirmed : {country.TotalConfirmed}</span>
                                <span className={styles.data}>Total Deaths : {country.TotalDeaths}</span>
                                <span className={styles.data}>Total Recovered : {country.TotalRecovered}</span>
                            </p>
                            
                        </div>
                    </div>

                    <div className={styles.graphsection}>
                        <LineChart updateData = {updateData}/>
                    </div>

                </div>
                
            </div>

       </div>
    )
}

export async function getServerSideProps({ params }) {
    const res = await fetch('https://api.covid19api.com/summary');
    const data = await res.json();
    const country = await data.Countries.filter(country => country.Slug == params.slug);
    let prevMonth = new Date(data.Date.split("T")[0]);
    prevMonth.setMonth(prevMonth.getMonth() - 1);
    prevMonth = JSON.stringify(prevMonth).split("T")[0].replace('"', '')
   
    const res1 = await fetch(`https://api.covid19api.com/country/${params.slug}/status/confirmed?from=${prevMonth}T00:00:00Z&to=${data.Date.split('T')[0]}T00:00:00Z`);
    const updateData = await res1.json();
 
    return {
      props: {country:country[0],updateData} // will be passed to the page component as props
    }
  }
